use official online container
NVIDIA/cloudai pull request #21
Opened 2024-05-19 12:47 UTC by jeffnvidia

## Summary
This MR is for using the official latest NeMo version

2024-05-21 06:13 UTC, srinivas212 commented
Needs PR template populated.

2024-05-21 06:14 UTC, srinivas212 commented
Pl rebase directly on main.

2024-05-21 09:04 UTC, jeffnvidia commented
> Pl rebase directly on main.

It was based on another PR of mine so that everything can be merged together

2024-05-23 14:37 UTC, amaslenn requested changes

2024-05-23 14:37 UTC, amaslenn commented on tests/test_slurm_system.py
I don't think these changes belong to this PR.

2024-05-30 09:16 UTC, jeffnvidia commented on tests/test_slurm_system.py
is this still relevant ?

2024-05-30 09:30 UTC, amaslenn commented on tests/test_slurm_system.py
No

2024-05-30 09:32 UTC, amaslenn approved these changes

2024-06-03 10:52 UTC, lappazos commented
@srinivas212 @TaekyungHeo please merge? was tested completlely

2024-06-03 11:54 UTC, merged